### ISSUE TITLE
Possibly redundant articles/templates/articles/display_folder.html

### ISSUE THREAD

**Issue by wade-cheng** [eshaanjoshi/readme#6]
is [articles/templates/articles/display_folder.html](https://github.com/eshaanjoshi/readme/blob/4f9629be903f2af4ddd215bf78f408898dffca3e/articles/templates/articles/display_folder.html) needed? Someone should check if this is being used

[UploadedImage](https://github.com/eshaanjoshi/readme/blob/1ef6924fbaa0afa10c5c16cb00f50d0f0e797605/articles/models.py#L79) model and other things that build on it might just take care of it.

**Comment by eshaanjoshi** [comment]
Was an open task I just finished
